name: Chaossynergy Images
on:
  pull_request:
    branches:
      - chaos
    paths-ignore:
      - "**.md"
      - ".github/workflows/*validate*.yml"
  push:
    branches:
      - chaos
    paths-ignore:
      - "**.md"
      - ".github/workflows/*validate*.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  build-image-chaos:
    name: Build Chaossynergy
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["chaossynergy"]
    with:
      brand_name: ${{ matrix.brand_name }}
      stream_name: stable
      image_flavors: "['main']"